#define DARKRED 0xC0C3
#define DARKYELLOW 0x8C09
#define ANTRACITE 0x4A69

#define BACKGROUND BLACK
#define NORMAL DARKYELLOW
#define HIGHLIGHT WHITE
#define ACCENT DARKRED
#define SECONDARY ANTRACITE